### ISSUE TITLE
a issues about ue4

### ISSUE THREAD

**Issue by guanginuestc** [RCalocaO/RCUtils#1]
sorry to make a issues here,because i couldn't find other way to contract you.
I found a bug in this commit,when study ue. why call a function after free the dll in [D3D12Adapter.cpp] line 1027?
if dxgi.dll is not already in current process before loadlibrary, the app will crash.
https://github.com/EpicGames/UnrealEngine/commit/67162c113228ef87495fdf117c195623f0f58818

**Comment by RCalocaO** [comment]
Oh interesting, I'll let the D3D12 owner know, thanks!
